{{- if .Values.canary.enabled -}}
{{- $fullName := include "orders.name" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  {{- with .Values.ingress.hosts }}
  hosts:
    {{ toYaml . | indent 4 }}
  {{- end }}
  http:
    - route:
        - destination:
            host: {{ template "orders.name" . }}
            subset: stable
        {{- if .Values.canary.enabled }}
          weight: {{ .Values.weight }}
        {{- end }}
        {{- if .Values.canary.enabled }}
        - destination:
            host: {{ template "orders.name" . }}
            subset: canary
          weight: {{ .Values.canary.weight }}
        {{- end }}
{{- end }}