# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- manual

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '709ff85a-d623-4d02-a684-6755d788791a'
  imageRepository: 'adventureworks/web'
  containerRegistry: 'jbens.azurecr.io'
  dockerfilePath: 'Adventureworks.Web/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'jbensa393-auth'
  dockerBuild: $(Build.SourcesDirectory)/Adventureworks
  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerBuild)/$(dockerfilePath)
        buildContext: $(dockerBuild)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
          
    - upload: $(Build.SourcesDirectory)/Adventureworks/Adventureworks.Web/charts
      artifact: helm
