apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: adventureworks
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: adventureworks
    spec:
      containers:
        - image: "adventureworks/web:dev"
          imagePullPolicy: IfNotPresent
          name: web
          ports:
            - containerPort: 80
          livenessProbe: 
            httpGet:
              path: /api/system/live
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/system/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
          resources:
              limits:
                cpu: 100m
                memory: 128Mi

#kubectl apply -f .\Adventureworks.Web\k8s.deploy.yaml