apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: adventureworks.web 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: adventureworks
    spec:
      containers:
        - name: frontend
          image: jbens.azurecr.io/adventureworks/web
          ports:
          - containerPort: 80
          livenessProbe: 
            httpGet:
              path: /api/system/live
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/system/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
          resources:
              limits:
                cpu: 100m
                memory: 128Mi
