{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gateway.name" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "gateway.name" . }}
    chart: {{ template "gateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{ toYaml . | indent 4 }}
  {{- end }}
spec:
  rules:
  - http:
     paths:
    {{- range .Values.ingress.paths }}
         - path: {{ .path }}
           backend:
             serviceName: {{ .backend.serviceName }}
             servicePort: {{ .backend.servicePort }}
    {{- end }}
{{- end }}