# apiVersion: v1
# kind: Secret
# metadata:
#   name: {{ .Release.Name }}-secrets
#   labels:
#     app: {{ template "documents.name" . }}
#     chart: {{ template "documents.chart" . }}
#     release: {{ .Release.Name }}
#     heritage: {{ .Release.Service }}
#   annotations:
#     "helm.sh/resource-policy": "keep"
# data:
#   DOCUMENT_STORAGE: {{ default "" .Values.secrets.connectionstring | b64enc | quote }}