{{- if .Values.ingress.enabled -}}
{{- $fullName := include "documents.name" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
  
spec:
  {{- with .Values.ingress.hosts }}
  hosts:
    {{ toYaml . | indent 4 }}
  {{- end }}
  gateways:
    - public-gateway
  http:
    - match:
        - uri:
            prefix: /api/
      route:
        - destination:
            port:
              number: 80
            host:  {{ include "documents.fullname" . }}
{{- end }}