environment: development

nameOverride: gateway
fullNameOverride: gateway

label:
  name: adventureworks


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "istio"
  paths:
    - path: /
      backend:
        serviceName: frontend
        servicePort: 80
    - path: /api/orders
      backend:
        serviceName: orders
        servicePort: 80
