apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "documentsprocessor.fullname" . }}
  labels:
    app: {{ template "documentsprocessor.name" . }}
    chart: {{ template "documentsprocessor.chart" . }}
    draft: {{ .Values.draft | default "draft-app" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    canary: "false"
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: {{ template "documentsprocessor.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "documentsprocessor.name" . }}
        draft: {{ .Values.draft | default "draft-app" }}
        release: {{ .Release.Name }}
        version: "{{ .Values.image.tag }}"
        canary: "false"
      annotations:
        buildID: "{{ .Values.image.tag }}"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef: 
                name: documents-secrets
          ports:
            - name: http
              containerPort: 80
          {{- if .Values.probes.enabled }}
          livenessProbe:
            httpGet:
              path: /api/system/live
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /api/system/ready
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 3
          {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}