kind: HorizontalPodAutoscaler 
apiVersion: autoscaling/v2beta1 
metadata: 
  name: {{ template "documentsprocessor.fullname" . }}-hpa 
spec: 
  maxReplicas: 10 
  minReplicas: 1 
  scaleTargetRef: 
    apiVersion: apps/v1beta2 
    kind: Deployment 
    name: {{ template "documentsprocessor.fullname" . }} 
  metrics: 
  - type: Resource 
    resource: 
      name: cpu 
      targetAverageUtilization: 80