environment: development

label:
  name: orders

image:
  repository: adventureworks/orders
  tag: dev
  name: orders
  pullPolicy: IfNotPresent
  port: 80

replicas: 2
weight: 90

service:
  type: ClusterIP
  port: 80

probes:
  enabled: true

canary:
  enabled: false
  tag: dev
  replicas: 1
  weight: 10

ingress:
  enabled: false
  annotations:
    # kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /api
  path: /api/
  hosts: 
    - "orders"
     
  tls: []
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
secrets: {}
resources: 
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi
   
nodeSelector:
   kubernetes.io/role: agent
   beta.kubernetes.io/os: linux
   type: virtual-kubelet

tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule

affinity: {}