apiVersion: v1
kind: Service
metadata:
  name: {{ template "frontend.name" . }}
  labels:
    app: {{ template "frontend.name" . }}
    chart: {{ template "frontend.chart" . }}
    release: {{ .Release.Name }}
    version: "{{ .Values.image.tag }}"
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.label.name }}
    release: {{ .Release.Name }}
