environment: development

label:
  name: frontend

image:
  repository: adventureworks/web
  tag: dev
  name: frontend
  pullPolicy: IfNotPresent
  port: 80

replicas: 2


service:
  type: ClusterIP
  port: 80

probes:
  enabled: true

ingress:
  enabled: true
  hosts:
    - 'kubernetes.docker.internal'
  annotations:
    kubernetes.io/ingress.class: "istio"
  paths:
    - path: /
      backend:
        serviceName: frontend
        servicePort: 80
    - path: /api/orders
      backend:
        serviceName: orders
        servicePort: 80
secrets: {}
resources: 
  limits:
   cpu: 100m
   memory: 128Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector:
   kubernetes.io/role: agent
   beta.kubernetes.io/os: linux
   type: virtual-kubelet

tolerations:
  - key: virtual-kubelet.io/provider
    operator: Exists
  - key: azure.com/aci
    effect: NoSchedule

affinity: {}